#!/usr/bin/env python3
"""Generate Q16 reciprocal lengths for integer radial pumps."""
import math
import pathlib

path = pathlib.Path(__file__).resolve().parent.parent / 'src/fluid_force_table.inc'
distances = list(range(64)) + list(range(64,4097,4))
values = [round(65536 / math.sqrt(d2 + 9)) for d2 in distances]
rows = [', '.join(map(str, values[i:i+16])) + ',' for i in range(0, len(values), 16)]
path.write_text('/* Generated by tools/generate-force-table.py: Q16 1/sqrt(d²+9).\n'
                '   Unit spacing below d²=64, then spacing 4 pixels². */\n'
                'static const uint16_t force_inverse_length[1073] = {\n' + '\n'.join(rows) + '\n};\n')

# Gameplay suction always uses radius 35. Fold its radial falloff into the
# reciprocal length so each cell needs no separate weight/amplitude product.
values = [round(65536 * max(0, 1-d2/(35*35)) / math.sqrt(d2+9)) for d2 in distances[:356]]
rows = [', '.join(map(str, values[i:i+16])) + ',' for i in range(0, len(values), 16)]
with path.open('a') as output:
    output.write('/* Q16 max(0,1-d²/35²)/sqrt(d²+9), same distance knots. */\n'
                 'static const uint16_t force_suction35_inverse[356] = {\n' + '\n'.join(rows) + '\n};\n')
