#!/usr/bin/env python3
"""Generate the positive RSP reciprocal-square-root ROM constants.

For each normalized mantissa/parity index, b is the largest integer satisfying
mantissa * b**2 < 2**44. This matches the hardware lookup modeled by ares:
https://github.com/ares-emulator/ares/blob/master/ares/n64/rsp/rsp.cpp
The arithmetic definition is reproduced here, not a copied emulator table.
"""
from math import isqrt
from pathlib import Path
values = []
for index in range(512):
    mantissa = (index + 512) >> (index & 1)
    value = isqrt(((1 << 44) - 1) // mantissa)
    values.append((value >> 1) & 65535)
rows = [", ".join(f"0x{x:04x}" for x in values[i:i+8]) for i in range(0,512,8)]
Path(__file__).resolve().parent.parent.joinpath("src/rsp_rsqrt_table.inc").write_text(
    "/* Generated by tools/generate-rsqrt.py. */\nstatic const uint16_t rsp_rsqrt_table[512]={\n    "
    + ",\n    ".join(rows) + "\n};\n")
