#!/usr/bin/env python3
"""Generate Q16 reciprocal lengths for the experimental integer radial pump."""
import math
import pathlib

path = pathlib.Path(__file__).resolve().parent.parent / 'src/fluid_force_table.inc'
distances = list(range(64)) + list(range(64,4097,4))
values = [round(65536 / math.sqrt(d2 + 9)) for d2 in distances]
rows = [', '.join(map(str, values[i:i+16])) + ',' for i in range(0, len(values), 16)]
path.write_text('/* Generated by tools/generate-force-table.py: Q16 1/sqrt(d²+9).\n'
                '   Unit spacing below d²=64, then spacing 4 pixels². */\n'
                'static const uint16_t force_inverse_length[1073] = {\n' + '\n'.join(rows) + '\n};\n')
