#!/usr/bin/env python3
"""Generate the positive RSP integer reciprocal lookup from its arithmetic definition."""
from pathlib import Path
values = [65535] + [(((1 << 34) // (index + 512) + 1) >> 8) & 65535 for index in range(1,512)]
rows = [', '.join(f'0x{x:04x}' for x in values[i:i+8]) for i in range(0,512,8)]
Path(__file__).resolve().parent.parent.joinpath('src/rsp_reciprocal_table.inc').write_text(
    '/* Generated by tools/generate-reciprocal.py. */\nstatic const uint16_t rsp_reciprocal_table[512]={\n'
    + ',\n'.join(rows) + '\n};\n')
