#!/usr/bin/env python3
"""Build the checked-in PCM bank from CC0 originals. Requires Python + ffmpeg.
Normal ROM builds use sound_bank.inc directly; no downloads or converter needed.
"""
from pathlib import Path
import array, math, struct, subprocess, sys, wave
ROOT=Path(__file__).resolve().parent.parent
RATE=16000

def load(name, filters=''):
    cmd=['ffmpeg','-v','error','-i',str(ROOT/'assets/audio/source'/f'{name}.ogg'),
         '-ac','1','-ar',str(RATE)]
    if filters: cmd+=['-af',filters]
    raw=subprocess.check_output(cmd+['-f','s16le','-'])
    a=array.array('h',raw)
    if sys.byteorder!='little': a.byteswap()
    return [v/32768 for v in a]

def normalize(a, peak=.8):
    mean=sum(a)/len(a); a=[v-mean for v in a]
    scale=peak/max(abs(v) for v in a)
    return [v*scale for v in a]

def shot(name,duration,filters=''):
    a=load(name,filters)
    first=next((i for i,v in enumerate(a) if abs(v)>.012),0)
    a=a[max(0,first-32):][:int(duration*RATE)]
    a=normalize(a)
    for i in range(len(a)):
        a[i]*=min(1,i/32,(len(a)-1-i)/320)
    return a

def loop(name, offset, duration, filters):
    a=load(name,filters); a=a[int(offset*RATE):int((offset+duration)*RATE)]
    n=int(.06*RATE)
    # Overlap the tail into the head, then rotate past the overlap. Seamless wrap.
    cross=[a[-n+i]*(1-i/n)+a[i]*(i/n) for i in range(n)]
    return normalize(cross+a[n:-n],.7)

bank={
 'bat':shot('impactGeneric_light_000',.16,'lowpass=f=5500'),
 'wall':shot('impactMetal_light_002',.22,'lowpass=f=4500'),
 'goal':shot('lowDown',.7,'asetrate=32000,aresample=16000,lowpass=f=4000'),
 'select':shot('threeTone2',.12,'asetrate=60000,aresample=16000,lowpass=f=4500'),
 'back':shot('lowDown',.16,'lowpass=f=3000'),
 'jet':loop('thrusterFire_000',.6,.75,'highpass=f=140,lowpass=f=3200'),
}
# Keep the force-field attack once, then morph over 1.2 seconds into a soft
# steady hum. Only the final one-second sustain repeats, never the attack.
source=normalize(load('forceField_000','lowpass=f=2300'),.7)
texture=loop('forceField_000',.15,.8,'lowpass=f=550')
sustain=[]
for i in range(RATE):
    t=i/RATE
    grain=texture[int(t*len(texture))]
    sustain.append(.17*math.sin(2*math.pi*90*t)+.055*math.sin(2*math.pi*180*t)
                   +.025*math.sin(2*math.pi*137*t)+grain*.035)
intro=[]
intro_length=int(1.2*RATE)
for i in range(intro_length):
    t=i/intro_length
    blend=t*t*(3-2*t)
    # Choose sustain phase so the end of the intro joins sustain[0] seamlessly.
    tail=sustain[(i-intro_length)%RATE]
    intro.append((source[i%len(source)]*(1-blend)+tail*blend)*min(1,i/160))
bank['suction']=intro+sustain
# Stock three-note cue with a quiet delayed repeat and a short lead-in so the
# final goal remains audible. No music or samples from GoldenEye are copied.
base=shot('threeTone2',1.1,'lowpass=f=4800')
win=[0.]*(int(.15*RATE)+len(base)+int(.18*RATE))
for i,v in enumerate(base):
    win[i+int(.15*RATE)]+=v*.8
    win[i+int(.33*RATE)]+=v*.25
bank['win']=win
# A metallic crack followed by two fading, lower-pitched sputters.
crack=shot('impactMetal_light_002',.18,'highpass=f=500,lowpass=f=6000')
sputter=shot('lowDown',.22,'asetrate=12000,aresample=16000,lowpass=f=2400')
broken=[0.]*(int(.20*RATE)+len(sputter))
for i,v in enumerate(crack): broken[i]+=v
for delay,gain in ((.08,.6),(.20,.3)):
    for i,v in enumerate(sputter): broken[i+int(delay*RATE)]+=v*gain
bank['break']=normalize(broken)
out=[f'#define SUCTION_LOOP_START {intro_length}', '/* Generated by tools/prepare-audio.py; Kenney CC0 sources in assets/audio. */']
for name,a in bank.items():
    pcm=[max(-32767,min(32767,round(v*32767))) for v in a]
    out.append(f'static const int16_t pcm_{name}[] = {{')
    out.extend(','.join(str(v) for v in pcm[i:i+16])+',' for i in range(0,len(pcm),16))
    out.append('};')
    with wave.open(str(ROOT/'assets/audio'/f'{name}.wav'),'wb') as w:
        w.setparams((1,2,RATE,len(pcm),'NONE','not compressed'))
        w.writeframes(struct.pack('<'+'h'*len(pcm),*pcm))
(ROOT/'src/sound_bank.inc').write_text('\n'.join(out)+'\n')
print('PCM bank:',sum(len(a)*2 for a in bank.values()),'bytes')
